### ISSUE TITLE
Newbie Quesiton: Can I use angel_websocket flutter client to connect to other WebSocket Servers?

### ISSUE THREAD

**Issue by sgon00** [angel-dart/websocket#44]
Sorry to interrupt you and I am not sure if I can ask a question in the issues here. 
Is that OK to use `package:angel_websocket/flutter.dart` to connect to other general WebSocket Servers which are not written in Dart and angel_websocket?
I am a newbie in dart/flutter and trying to understand how to use websocket in flutter. I can not find any other examples online except angel_websocket, but unfortunately, I am not using angel-dart backend. Thank you very much for your help.

**Comment by thosakwe** [comment]
This package will only work with Angel backends. The reason is that the event dispatch protocol Angel uses resembles the "service" pattern, a main part of Angel. This makes abstractions like `app.service('api/todos')` possible on the client side. 

`dart:io` exposes a `WebSocket.connect` function you can use to connect to any arbitrary backend.
